#
dist: bionic
language: cpp
compiler:
   - gcc
#  - clang

jobs:
  include:
    - os: linux
      script:
      - sudo apt-get update -qq
      - sudo apt-get install cmake
      - (cmake  . || (echo XXX CMakeOutput.log; cat /home/travis/build/simgrid/simgrid/CMakeFiles/CMakeOutput.log; echo XXX CMakeError.log;cat /home/travis/build/simgrid/simgrid/CMakeFiles/CMakeError.log; exit 1))
      - make -j$(nproc) VERBOSE=1 all && ctest
#    - os: osx
#      osx_image: xcode11.4
#      script:
#      - export LIBRARY_PATH=/usr/local/lib/gcc/9
#      - cmake .
#      - make -j2 VERBOSE=1 all
notifications:
  recipients:
    - martin.quinson@ens-rennes.fr
  email:
    on_success: change
    on_failure: always
#  irc:
#    on_success: change
#    on_failure: always
#    channels:
#      - "irc.debian.org#simgrid"
  template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
