version: 2.1
 
jobs:
  build:
    docker:
      - image: simgrid/build-deps
    steps:
      - checkout
      - run:
          name: sonarcloud needs some extra love
          command: |
            apt update && apt install -y curl
            wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
            unzip build-wrapper-linux-x86.zip
            cp build-wrapper-linux-x86/libinterceptor-x86_64.so build-wrapper-linux-x86/libinterceptor-haswell.so
      - run:
          name: Install dependencies and build project
          command: |
            cmake .
            ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir /tmp make VERBOSE=1
            ./tiny_simgrid 1
            ./tiny_simgrid 2
            ./tiny_simgrid 3
            ./tiny_simgrid 4
            ./tiny_simgrid 5
            ./tiny_simgrid 6
            ./tiny_simgrid 7
            ./tiny_simgrid 8
            ./tiny_simgrid 9
            ./tiny_simgrid 10
            ./tiny_simgrid 11
            ./tiny_simgrid 12
            ./tiny_simgrid 13
            ./tiny_simgrid 14
            ./tiny_simgrid 15
            ./tiny_simgrid 16
            ./tiny_simgrid 17
            ctest || true
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
